export const nhlTeams = [
  { abbrev: "ANA", name: "Anaheim Ducks", logo: "https://assets.nhle.com/logos/nhl/svg/ANA_light.svg" , league: "NHL" },
  { abbrev: "BOS", name: "Boston Bruins", logo: "https://assets.nhle.com/logos/nhl/svg/BOS_light.svg" , league: "NHL" },
  { abbrev: "BUF", name: "Buffalo Sabres", logo: "https://assets.nhle.com/logos/nhl/svg/BUF_light.svg" , league: "NHL" },
  { abbrev: "CAR", name: "Carolina Hurricanes", logo: "https://assets.nhle.com/logos/nhl/svg/CAR_light.svg" , league: "NHL" },
  { abbrev: "CBJ", name: "Columbus Blue Jackets", logo: "https://assets.nhle.com/logos/nhl/svg/CBJ_light.svg" , league: "NHL" },
  { abbrev: "CGY", name: "Calgary Flames", logo: "https://assets.nhle.com/logos/nhl/svg/CGY_light.svg" , league: "NHL" },
  { abbrev: "CHI", name: "Chicago Blackhawks", logo: "https://assets.nhle.com/logos/nhl/svg/CHI_light.svg" , league: "NHL" },
  { abbrev: "COL", name: "Colorado Avalanche", logo: "https://assets.nhle.com/logos/nhl/svg/COL_light.svg" , league: "NHL" },
  { abbrev: "DAL", name: "Dallas Stars", logo: "https://assets.nhle.com/logos/nhl/svg/DAL_light.svg" , league: "NHL" },
  { abbrev: "DET", name: "Detroit Red Wings", logo: "https://assets.nhle.com/logos/nhl/svg/DET_light.svg" , league: "NHL" },
  { abbrev: "EDM", name: "Edmonton Oilers", logo: "https://assets.nhle.com/logos/nhl/svg/EDM_light.svg" , league: "NHL" },
  { abbrev: "FLA", name: "Florida Panthers", logo: "https://assets.nhle.com/logos/nhl/svg/FLA_light.svg" , league: "NHL" },
  { abbrev: "LAK", name: "Los Angeles Kings", logo: "https://assets.nhle.com/logos/nhl/svg/LAK_light.svg" , league: "NHL" },
  { abbrev: "MIN", name: "Minnesota Wild", logo: "https://assets.nhle.com/logos/nhl/svg/MIN_light.svg" , league: "NHL" },
  { abbrev: "MTL", name: "Montréal Canadiens", logo: "https://assets.nhle.com/logos/nhl/svg/MTL_light.svg" , league: "NHL" },
  { abbrev: "NJD", name: "New Jersey Devils", logo: "https://assets.nhle.com/logos/nhl/svg/NJD_light.svg" , league: "NHL" },
  { abbrev: "NSH", name: "Nashville Predators", logo: "https://assets.nhle.com/logos/nhl/svg/NSH_light.svg" , league: "NHL" },
  { abbrev: "NYI", name: "New York Islanders", logo: "https://assets.nhle.com/logos/nhl/svg/NYI_light.svg" , league: "NHL" },
  { abbrev: "NYR", name: "New York Rangers", logo: "https://assets.nhle.com/logos/nhl/svg/NYR_light.svg" , league: "NHL" },
  { abbrev: "OTT", name: "Ottawa Senators", logo: "https://assets.nhle.com/logos/nhl/svg/OTT_light.svg" , league: "NHL" },
  { abbrev: "PHI", name: "Philadelphia Flyers", logo: "https://assets.nhle.com/logos/nhl/svg/PHI_light.svg" , league: "NHL" },
  { abbrev: "PIT", name: "Pittsburgh Penguins", logo: "https://assets.nhle.com/logos/nhl/svg/PIT_light.svg" , league: "NHL" },
  { abbrev: "SEA", name: "Seattle Kraken", logo: "https://assets.nhle.com/logos/nhl/svg/SEA_light.svg" , league: "NHL" },
  { abbrev: "SJS", name: "San Jose Sharks", logo: "https://assets.nhle.com/logos/nhl/svg/SJS_light.svg" , league: "NHL" },
  { abbrev: "STL", name: "St. Louis Blues", logo: "https://assets.nhle.com/logos/nhl/svg/STL_light.svg" , league: "NHL" },
  { abbrev: "TBL", name: "Tampa Bay Lightning", logo: "https://assets.nhle.com/logos/nhl/svg/TBL_light.svg" , league: "NHL" },
  { abbrev: "TOR", name: "Toronto Maple Leafs", logo: "https://assets.nhle.com/logos/nhl/svg/TOR_light.svg" , league: "NHL" },
  { abbrev: "UTA", name: "Utah Mammoth", logo: "https://assets.nhle.com/logos/nhl/svg/UTA_light.svg" , league: "NHL" },
  { abbrev: "VAN", name: "Vancouver Canucks", logo: "https://assets.nhle.com/logos/nhl/svg/VAN_light.svg" , league: "NHL" },
  { abbrev: "VGK", name: "Vegas Golden Knights", logo: "https://assets.nhle.com/logos/nhl/svg/VGK_light.svg" , league: "NHL" },
  { abbrev: "WSH", name: "Washington Capitals", logo: "https://assets.nhle.com/logos/nhl/svg/WSH_light.svg" , league: "NHL" },
  { abbrev: "WPG", name: "Winnipeg Jets", logo: "https://assets.nhle.com/logos/nhl/svg/WPG_light.svg" , league: "NHL" },
];